export const FACILITY_TERMS_DATA = {
  termsAndConsent: [
    'facilityTerms.termsAndConsent.paragraph1',
    'facilityTerms.termsAndConsent.paragraph2',
    'facilityTerms.termsAndConsent.paragraph3',
    'facilityTerms.termsAndConsent.paragraph4',
    'facilityTerms.termsAndConsent.paragraph5',
    'facilityTerms.termsAndConsent.paragraph6',
    'facilityTerms.termsAndConsent.paragraph7',
    'facilityTerms.termsAndConsent.paragraph8',
    'facilityTerms.termsAndConsent.paragraph9',
    'facilityTerms.termsAndConsent.paragraph10',
    'facilityTerms.termsAndConsent.paragraph11',
    'facilityTerms.termsAndConsent.paragraph12',
    'facilityTerms.termsAndConsent.paragraph13',
    'facilityTerms.termsAndConsent.paragraph14',
    'facilityTerms.termsAndConsent.paragraph15',
    'facilityTerms.termsAndConsent.paragraph16',
  ],
  title: 'facilityTerms.title',
  checkboxLabel: 'facilityTerms.checkboxLabel',
  checkboxLabel2: 'facilityTerms.checkboxLabel2',
  cancelButton: 'facilityTerms.cancelButton',
  acceptButton: 'facilityTerms.acceptButton',
};
