export interface ServiceCode {
    id: number;
    code: number;
    text: string;
    type: "normal" | "warning" | "error";
}

export interface OperationType {
    id: number;
    code: number;
    text: string;
    type: "normal" | "warning" | "error";
}

export interface CallReason {
    id: number;
    cause: string;
    causeCode: number;
    type: "normal" | "warning" | "error";
}

export const getServiceCodes = (): ServiceCode[] => [
    { id: 1, code: 1, text: "MANUAL STOP", type: "warning" },
    { id: 2, code: 4, text: "HEAT STOR AGE IS FULL", type: "normal" },
    { id: 3, code: 5, text: "HEAT STOR AGE IS ⅔ FULL", type: "normal" },
    { id: 4, code: 6, text: "LOW ELECTRICITY CONSUMPTION", type: "warning" },
    { id: 5, code: 7, text: "NO POWER PRODUCTION", type: "normal" },
    { id: 6, code: 9, text: "AUTOMATIC OIL CHANGE", type: "normal" },
    { id: 7, code: 10, text: "FAULTY OIL PRESSURE SENSOR", type: "error" },
    { id: 8, code: 12, text: "NO OIL PRESSURE", type: "error" },
    { id: 9, code: 17, text: "LOW POWER PRODUCTION DURING CALIBRATION", type: "warning" },
    { id: 10, code: 18, text: "HIGH POWER PRODUCTION DURING CALIBRATION", type: "warning" },
    { id: 11, code: 19, text: "PRODUCTION STOP DURING CALIBRATION", type: "error" },
    { id: 12, code: 20, text: "OIL PRESSURE ALARM", type: "error" },
    { id: 13, code: 21, text: "BOIL ALARM (ENGINE)", type: "error" },
    { id: 14, code: 22, text: "NO ELECTRICITY CONSUMPTION", type: "normal" },
    { id: 15, code: 23, text: "OIL SUMP NOT EMPTY AFTER DRAINING", type: "normal" },
    { id: 16, code: 24, text: "CODE 24 – LOW POWER PRODUCTION", type: "warning" },
    { id: 17, code: 29, text: "OIL SUMP NOT FULL AFTER FILLING", type: "normal" },
    { id: 18, code: 33, text: "OIL SUMP IS ALREADY FULL", type: "normal" },
    { id: 19, code: 39, text: "AUTOMATIC OIL CHANGE", type: "normal" },
    { id: 20, code: 47, text: "ALTERNATIVE HEAT SOURCE", type: "normal" },
    { id: 21, code: 48, text: "LOW TARIFF STOP", type: "error" },
    { id: 22, code: 49, text: "LOW PRIORITY (STAND-BY NIGHT)", type: "warning" },
    { id: 23, code: 55, text: "AUX-ALARM", type: "error" },
    { id: 24, code: 56, text: "UNSTABLE POWERPRODUCTION, START", type: "normal" },
    { id: 25, code: 58, text: "UNSTABLE POWER OUTPUT, FALLING DURING CALIBRATION", type: "normal" },
    { id: 26, code: 61, text: "LOW GASPRESSURE", type: "warning" },
    { id: 27, code: 62, text: "EXHAUSTGAS BACKPRESSURE", type: "normal" },
    { id: 28, code: 63, text: "NO VACUUM", type: "normal" },
    { id: 29, code: 64, text: "PERFORMANCE CONTROL ALARM", type: "error" },
    { id: 30, code: 65, text: "TOO HIGH ENGINE COOLING WATER TEMPERATURE", type: "warning" },
    { id: 31, code: 66, text: "TOO HIGH TEMPERATURE IN EXHAUST GAS EXCHANGER", type: "warning" },
    { id: 32, code: 67, text: "TOO HIGH ENGINE CABINET TEMPERATURE", type: "warning" },
    { id: 33, code: 68, text: "CODE 68 – TOO HIGH TMV TEMPERATURE", type: "warning" },
    { id: 34, code: 70, text: "STOP FOR MANUAL OIL CHANGE", type: "error" },
    { id: 35, code: 71, text: "OIL SENSOR FAULT", type: "error" },
    { id: 36, code: 72, text: "5 VOLT FAULT - MOTHERBOARD", type: "error" },
    { id: 37, code: 73, text: "CODE 73 – 24 VOLT FAULT - MOTHERBOARD", type: "error" },
    { id: 38, code: 74, text: "24 VOLT OVER CURRENT - MOTHERBOARD", type: "normal" },
    { id: 39, code: 75, text: "24 VOLT OVER CURRENT – DISPLAY BOARD", type: "normal" },
    { id: 40, code: 76, text: "SOFT STARTER/SMART STARTER TM", type: "normal" },
    { id: 41, code: 77, text: "GAS ALARM", type: "error" },
    { id: 42, code: 78, text: "START – STORAGE COLD", type: "normal" },
    { id: 43, code: 79, text: "START – OTHER CONDITIONS", type: "normal" },
    { id: 44, code: 80, text: "SYSTEM RESTART", type: "normal" },
    { id: 45, code: 81, text: "ALARM ACKNOWLEDGED", type: "error" },
    { id: 46, code: 82, text: "START, FORCED", type: "normal" },
    { id: 47, code: 83, text: "GRID FAULT", type: "error" },
    { id: 48, code: 84, text: "OIL LEVEL NOT SUFFICIENT AFTER 5 ATTEMPTS", type: "normal" },
    { id: 49, code: 85, text: "MANUAL START", type: "warning" },
    { id: 50, code: 86, text: "NO POWER PRODUCTION IN CALIBRATION", type: "normal" },
    { id: 51, code: 87, text: "START DUE TO POWER SALES", type: "normal" },
    { id: 52, code: 88, text: "OUTSIDE REGULATING RANGE", type: "normal" },
    { id: 53, code: 89, text: "FORCED WAITING POSITION", type: "normal" },
    { id: 54, code: 94, text: "FIRE ALARM", type: "error" },
    { id: 55, code: 95, text: "NO COOLING", type: "normal" },
    { id: 56, code: 96, text: "PUMP FUSE –Q-HEATDISTRIBUTOR", type: "error" },
    { id: 57, code: 97, text: "ENGINE VALVE-NO POWER CONSUMPTION", type: "normal" },
    { id: 58, code: 98, text: "5 VOLT ABSENT-HEATDISTRIBUTOR", type: "error" },
    { id: 59, code: 99, text: "24 VOLT ABSENT-HEATDISTRIBUTOR", type: "error" },
    { id: 60, code: 100, text: "FAULT Y ENDSWITCH-ENGINE VALVE", type: "warning" },
    { id: 61, code: 101, text: "FAULT Y ENDSWITCH-FLOWCONTROL VALVE", type: "warning" },
    { id: 62, code: 102, text: "DEFECTIVE TEMPERATURE SENSOR- Q-HEATDISTRIBUTOR", type: "warning" },
    { id: 63, code: 103, text: "PT 100 SENSOR DEFECTIVE", type: "warning" },
    { id: 64, code: 104, text: "VPP MODE 0", type: "normal" },
    { id: 65, code: 105, text: "VPP MODE 1", type: "normal" },
    { id: 66, code: 106, text: "VPP MODE 2", type: "normal" },
    { id: 67, code: 107, text: "VPP MODE 3", type: "normal" },
    { id: 68, code: 108, text: "VPP MODE 4", type: "normal" },
    { id: 69, code: 109, text: "VPP MODE 5", type: "normal" },
    { id: 70, code: 110, text: "Q-NET WORK UNIT MISSING", type: "warning" },
    { id: 71, code: 111, text: "NO POWER CONSUMPTION-FLOW VALVE", type: "warning" },
    { id: 72, code: 112, text: "MISFIRE", type: "error" },
    { id: 73, code: 113, text: "START IN ESC-MODE", type: "normal" },
    { id: 74, code: 114, text: "PHASE MONITORING, TOO HIGH VOLTAGE", type: "warning" },
    { id: 75, code: 115, text: "PHASE MONITORING, TOO LOW VOLTAGE", type: "warning" },
    { id: 76, code: 116, text: "PHASE MONITORING, TOO HIGH FREQUENCY", type: "warning" },
    { id: 77, code: 117, text: "PHASE MONITORING, TOO LOW FREQUENCY", type: "warning" },
    { id: 78, code: 118, text: "PHASE MONITORING, LOW QUALITY", type: "warning" },
    { id: 79, code: 119, text: "PHASE MONITORING, PHASE SEQUENCE", type: "warning" },
    { id: 80, code: 120, text: "TIME FOR SERVICE", type: "warning" },
    { id: 81, code: 121, text: "SERVICE IMMINIENT", type: "warning" },
    { id: 82, code: 122, text: "LAMBDA SENSOR ERROR", type: "error" },
    { id: 83, code: 123, text: "MAP SENSOR ERROR", type: "error" },
    { id: 84, code: 124, text: "INJECTOR ERROR", type: "error" },
    { id: 85, code: 125, text: "CAM-SENSOR ERROR", type: "error" },
    { id: 86, code: 126, text: "CRANK-SENSOR ERROR", type: "error" },
    { id: 87, code: 127, text: "IGNITION MODULE ERROR", type: "error" },
    { id: 88, code: 128, text: "OVERSPEED", type: "error" },
    { id: 89, code: 129, text: "ECU SELF TEST ERROR", type: "warning" },
    { id: 90, code: 130, text: "VENTURI MAX POSITION", type: "warning" },
    { id: 91, code: 131, text: "LOAD SHARER-FORCED STANDBY", type: "normal" },
    { id: 92, code: 132, text: "HEAT CONTROL-SENSOR DEVIATION", type: "warning" },
    { id: 93, code: 133, text: "SERVICE DONE", type: "warning" },
    { id: 94, code: 134, text: "FLOW MASTER PUMP FUSE", type: "warning" },
    { id: 95, code: 135, text: "LOW COOLANT LEVEL", type: "warning" },
    { id: 96, code: 136, text: "STANDBY, LOW LOAD", type: "normal" },
    { id: 97, code: 137, text: "STATIC AL DATA CORRECTION", type: "warning" },
    { id: 98, code: 138, text: "SERVICE TIME BALANCING", type: "warning" },
    { id: 99, code: 139, text: "GRID CODE STOP IN MIN. PRODUCTION", type: "normal" },
    { id: 100, code: 140, text: "WRONG DIRECTION OF ENGINE ROTATION", type: "error" },
    { id: 101, code: 141, text: "SURGE PROTECTOR NEEDS SERVICE", type: "warning" },
    { id: 102, code: 142, text: "HEAT PUMP ALARM", type: "warning" },
    { id: 103, code: 143, text: "BOILER RELEASED", type: "normal" },
    { id: 104, code: 144, text: "BOILER NOT RELEASED", type: "normal" },
    { id: 105, code: 145, text: "PROLONGED STANDBY", type: "normal" },
    { id: 106, code: 146, text: "SMART STARTER ALARM", type: "error" },
    { id: 107, code: 147, text: "NO FLOW IN STORAGE CIRCUIT", type: "error" },
    { id: 108, code: 148, text: "NO FLOW IN PRIMARY ENGINE CIRCUIT", type: "error" },
    { id: 109, code: 149, text: "VALVE OPERATED BY STEPPER MOTOR-APPEARS SEIZED", type: "error" },
    { id: 110, code: 150, text: "VALVE OPERATED BY STEPPERMOTOR-NOT OPENING", type: "error" },
    { id: 111, code: 151, text: "TEMPERATURE SENSOR TLV AND TMV HAS ERRATIC BEEN SWAPPED", type: "error" },
    { id: 112, code: 152, text: "VALVE OPERATED BY STEPPER MOTOR-UNABLE TO OPEN FULLY", type: "normal" },
    { id: 113, code: 153, text: "VALVE OPERATED BY STEPPER MOTOR-UNABLE TO CLOSE FULLY", type: "normal" },
    { id: 114, code: 154, text: "PLATE HEAT EXCHANGER-LOW CAPACITY", type: "warning" },
    { id: 115, code: 155, text: "TOO MANY START/STOP SEQUENCES", type: "error" },
    { id: 116, code: 156, text: "LOW COOLANT PRESSURE", type: "error" },
    { id: 117, code: 157, text: "ALC PUMP FAILURE", type: "warning" },
    { id: 118, code: 158, text: "ALC SENSOR ERROR", type: "warning" },
    { id: 119, code: 159, text: "VPP MODE 6", type: "normal" },
    { id: 120, code: 160, text: "HEAT CONTROL CRITICAL SENSOR ERROR", type: "error" }
];

export const getOperationTypes = (t: (key: string) => string): OperationType[] => [
    { id: 1, code: 0, text: "Full Stop", type: "warning" },
    { id: 2, code: 1, text: "Shutdown due to emergency stop", type: "error" },
    { id: 3, code: 2, text: "Step adjustment after system start-up", type: "normal" },
    { id: 4, code: 3, text: "Start-up (15 sec)", type: "normal" },
    { id: 5, code: 4, text: "Start-up (star)", type: "normal" },
    { id: 6, code: 5, text: "Start-up (* OK)", type: "normal" },
    { id: 7, code: 6, text: "Start-up (15 sec)", type: "normal" },
    { id: 8, code: 8, text: "Heating element calib.", type: "normal" },
    { id: 9, code: 9, text: "Calibration", type: "normal" },
    { id: 10, code: 10, text: "Normal operation", type: "normal" },
    { id: 11, code: 21, text: "Shutdown due to manual stop", type: "warning" },
    { id: 12, code: 22, text: "Ventilating (restart)", type: "normal" },
    { id: 13, code: 31, text: "Shutdown due to stand-by", type: "normal" },
    { id: 14, code: 40, text: "Stand-by", type: "normal" },
    { id: 15, code: 45, text: "Manual oil change/45", type: "warning" },
    { id: 16, code: 46, text: "Manual oil change/46", type: "warning" },
    { id: 17, code: 47, text: "Manual oil change/47", type: "warning" },
    { id: 18, code: 48, text: "Manual oil change/48", type: "warning" },
    { id: 19, code: 49, text: "Manual oil change/49", type: "warning" },
    { id: 20, code: 56, text: "Auto oil change/56", type: "normal" },
    { id: 21, code: 58, text: "Auto oil change/58", type: "normal" },
    { id: 22, code: 60, text: "EMERGENCY STOP (oil change)", type: "error" },
    { id: 23, code: 61, text: "EMERGENCY STOP ", type: "error" },
    { id: 24, code: 62, text: "EMERGENCY STOP (oil change)", type: "error" },
    { id: 25, code: 70, text: "	SERVICE ", type: "warning" },
    { id: 26, code: 71, text: "Electricity Sale", type: "normal" },
    { id: 27, code: 72, text: "Ventilation", type: "normal" },
    { id: 28, code: 73, text: "Freq response", type: "normal" },
    { id: 29, code: 74, text: "HRTM", type: "normal" },
    { id: 30, code: 75, text: "FNN limit", type: "normal" },
]

export const getCallReason = (t: (key: string) => string): CallReason[] => [
    { id: 1, cause: "System restarted", causeCode: 0, type: "warning" },
    { id: 2, cause: "Normal (8/24)", causeCode: 1, type: "normal" },
    { id: 3, cause: "ALARM", causeCode: 2, type: "error" },
    { id: 4, cause: "Manual additional call", causeCode: 3, type: "warning" },
    { id: 5, cause: "Restarted after Full Stop", causeCode: 4, type: "warning" },
    { id: 6, cause: "SMS", causeCode: 5, type: "warning" },
    { id: 7, cause: "Data correction", causeCode: 7, type: "warning" },
]